name: Deploy to QA

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print QA environment variables
        run: |
          echo "QA DB Host: $QA_DB_HOST"
          echo "QA DB Password: ${{ secrets.DB_PASSWORD }}"
        env:
          QA_DB_HOST: ${{ vars.QA_DB_HOST }}
