name: "Pr Opened"
on:
  pull_request:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref,'refs/heads/feat') || contains(github.ref,'refs/heads/karina')}}
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: date