name: "Pr Opened"
on:
  pull_request:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    if: "${{ github.ref == 'refs/heads/karina' }}"
    steps:
      - uses: actions/checkout@v1
      - name: "${{ github.ref }} "
        run: date