name: "Pr Opened"
on:
  pull_request:
    banches:
      - "master"
jobs:
  test:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: date