name: "Pr Opened"
on:
  pull_request:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ contains(github.head_ref,'alpha') || contains(github.head_ref,'beta') || contains(github.head_ref,'feat') || contains(github.head_ref,'prerelease') }}
    steps:
      - uses: actions/checkout@v1
      - name: "E nui"
        run: date
      - run: env
        
    
  outro:
    uses: ./.github/workflows/reusar.yaml
    with:
      user: "Diego"