name: "Pr Opened"
on:
  pull_request:
    branches:
      - "master"
jobs:
  test:
    if: contains(${{ github.ref }}, 'feat') or contains(${{ github.ref }}, 'release') or contains(${{ github.ref }}, 'alpha')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: date