name: "Pr Opened"
on:
  pull_request:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ contains(github.head_ref,'karina' }}
    steps:
      - uses: actions/checkout@v1
      - name: "${{ github.ref }} "
        run: date
      - run: env