name: Notify Microsoft Teams

on:
  push:
    branches:
      - main # or 'dev', etc.

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" \
               -d '{
                    "title": "GitHub Action Notification",
                    "text": "🚀 A new push was made to the `main` branch by '${{ github.actor }}'.\nCommit: `${{ github.sha }}`"
                   }' \
               ${{ secrets.TEAMS_WEBHOOK_URL }}
