name: "Pr Opened"
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Release Action
        uses: codfish/semantic-release-action@v1
