name: Reusable workflow example
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  ola:
    name: Nome e data
    runs-on: ubuntu-latest
    
    steps:
      - name: "Inicio"
        run: date
      - name: "Bla"
        run: echo ${{ inputs.name }}
      - name: "Fim"
        run: date
