name: WebTest
run-name: WebTest
on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   sparse-checkout: |
        #     .github/actions
        # #   path: .github/actions

      - name: WebTest
        uses: ./.github/actions/web
        id: WebTest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.ref }}
