name: WebTest
run-name: WebTest
on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
          path: actions

      - name: WebTest
        uses: ./web
        id: WebTest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
